[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

[colors.cursor]
text = "#686b70"
cursor = "CellForeground"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.9

[window.padding]
x = 2
y = 2
